services:
  db:
    image: postgres:16.2
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data
      - ./database/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - localnetwork
    env_file:
      - ./.env

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - localnetwork
    env_file:
      - ./.env

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
      - db
    networks:
      - localnetwork
    ports:
      - '80:80'
    env_file:
      - ./.env

volumes:
  postgres:

networks:
  localnetwork:
